name: CI

on:
  push:
    branches:
      - "*"
    tags-ignore:
      - "alpha-*"
      - "release-*"

jobs:
  build:
    runs-on: ubuntu-latest

    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - uses: ./.github/workflows/actions/build-env-setup

      - name: Build
        run: yarn build
        shell: bash

      - name: Test
        run: yarn test
        shell: bash

      - name: step 2 - Add artifacts to publish to the temp folder
        run: |
          cd artifacts
          echo 'alpha'    > alpha.html
          echo 'bravo'    > bravo.html
          echo 'charlie'  > charlie.html
          cd ..

      - name: Step 3 - Use the Upload Artifact GitHub Action
        uses: actions/upload-artifact@v3
        with:
          name: artifacts-for-download
          path: artifacts