name: Build and Deploy Production Library

on:
  push:
    tags:
      - "release-*"

jobs:
  build-and-deploy-production-library:
    runs-on: ubuntu-latest

    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure environment
        uses: ./.github/workflows/actions/build-env-setup

      - name: Install dependencies
        run: yarn install
        shell: bash

      - name: Build, Test, Package, Apply CI Vars
        run: yarn prepare-to-publish
        shell: bash

      - name: Deploy to NPMJS
        run: yarn publish
        shell: bash
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
